{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2b49585a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | default_exp testing.client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "066eedbe",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "from collections import namedtuple\n",
    "from unittest.mock import AsyncMock, MagicMock\n",
    "from typing import *\n",
    "import functools\n",
    "\n",
    "from fastcore.foundation import patch\n",
    "\n",
    "from fastkafka.application import FastKafka"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d59706d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pytest\n",
    "\n",
    "from pydantic import BaseModel, Field\n",
    "\n",
    "\n",
    "from fastkafka.helpers import create_missing_topics\n",
    "from fastkafka.testing import LocalKafkaBroker"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "70b54b2f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "@patch\n",
    "def create_mocks(self: FastKafka) -> None:\n",
    "    app_methods = [f for f, _ in self._consumers_store.values()] + [\n",
    "        f for f, _, _ in self._producers_store.values()\n",
    "    ]\n",
    "    self.AppMocks = namedtuple(\n",
    "        f\"{self.__class__.__name__}Mocks\", [f.__name__ for f in app_methods]\n",
    "    )\n",
    "    # todo: create Magicmock if needed\n",
    "    self.mocks = self.AppMocks(**{f.__name__: AsyncMock() for f in app_methods})\n",
    "\n",
    "    def add_mock(f: Callable[[...], Any], mock: AsyncMock) -> Callable[[...], Any]:\n",
    "        @functools.wraps(f)\n",
    "        async def async_inner(\n",
    "            *args, f: Callable[[...], Any] = f, mock: AsyncMock = mock, **kwargs\n",
    "        ) -> Any:\n",
    "            await mock(*args, **kwargs)\n",
    "            return await f(*args, **kwargs)\n",
    "\n",
    "        return async_inner\n",
    "\n",
    "    self._consumers_store = {\n",
    "        name: (\n",
    "            add_mock(f, getattr(self.mocks, f.__name__)),\n",
    "            kwargs,\n",
    "        )\n",
    "        for name, (f, kwargs) in self._consumers_store.items()\n",
    "    }\n",
    "    self._producers_store = {\n",
    "        name: (\n",
    "            add_mock(f, getattr(self.mocks, f.__name__)),\n",
    "            producer,\n",
    "            kwargs,\n",
    "        )\n",
    "        for name, (f, producer, kwargs) in self._producers_store.items()\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8eb00bb6",
   "metadata": {},
   "outputs": [],
   "source": [
    "class TestMsg(BaseModel):\n",
    "    msg: str = Field(...)\n",
    "\n",
    "def create_service(bootstrap_servers: str) -> FastKafka:\n",
    "    service = FastKafka(bootstrap_servers=bootstrap_servers)\n",
    "\n",
    "    @service.consumes()\n",
    "    async def on_preprocessed_signals(msg: TestMsg):\n",
    "        await to_predictions(TestMsg(msg=\"prediction\"))\n",
    "\n",
    "\n",
    "    @service.produces()\n",
    "    async def to_predictions(prediction: TestMsg) -> TestMsg:\n",
    "        print(f\"Sending prediction: {prediction}\")\n",
    "        return prediction\n",
    "    \n",
    "    return service"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "baea5bb5",
   "metadata": {},
   "outputs": [],
   "source": [
    "service = create_service(\"localhost:9092\")\n",
    "\n",
    "service.create_mocks()\n",
    "service.mocks.on_preprocessed_signals.assert_not_awaited()\n",
    "service.mocks.to_predictions.assert_not_awaited()\n",
    "service.create_mocks()\n",
    "service.mocks.on_preprocessed_signals.assert_not_awaited()\n",
    "service.mocks.to_predictions.assert_not_awaited()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e71d8282",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "class Tester(FastKafka):\n",
    "    def __init__(self, apps: List[FastKafka]):\n",
    "        self.apps = apps\n",
    "        super().__init__(bootstrap_servers=apps[0]._kafka_config[\"bootstrap_servers\"])\n",
    "        self.create_mirror()\n",
    "\n",
    "        @self.produces()\n",
    "        async def to_preprocessed_signals(msg: str) -> str:\n",
    "            print(f\"Producing msg {msg}\")\n",
    "            return msg\n",
    "        self.to_preprocessed_signals = to_preprocessed_signals\n",
    "\n",
    "        @self.consumes(auto_offset_reset=\"latest\")\n",
    "        async def on_predictions(msg: str):\n",
    "            pass\n",
    "\n",
    "    async def startup(self):\n",
    "        for app in self.apps:\n",
    "            app.create_mocks()\n",
    "            await app.startup()\n",
    "        \n",
    "        self.create_mocks()\n",
    "        await super().startup()\n",
    "        await asyncio.sleep(3)\n",
    "\n",
    "    async def shutdown(self):\n",
    "        await super().shutdown()\n",
    "        for app in self.apps.reverse():\n",
    "            await app.shutdown()\n",
    "        \n",
    "    def create_mirror(self):\n",
    "        pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "854735b2",
   "metadata": {},
   "outputs": [],
   "source": [
    "tester = Tester([create_service(\"localhost:9092\")])\n",
    "\n",
    "with pytest.raises(AttributeError) as e:\n",
    "    tester.mocks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "075f9455",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] fastkafka.testing: Java is already installed.\n",
      "[INFO] fastkafka.testing: But not exported to PATH, exporting...\n",
      "[INFO] fastkafka.testing: Kafka is already installed.\n",
      "[INFO] fastkafka.testing: But not exported to PATH, exporting...\n",
      "[INFO] fastkafka.testing: Starting zookeeper...\n",
      "[INFO] fastkafka.testing: Zookeeper started, sleeping for 5 seconds...\n",
      "[INFO] fastkafka.testing: Starting Kafka broker...\n",
      "[INFO] fastkafka.testing: Kafka broker started, sleeping for 5 seconds...\n",
      "[INFO] fastkafka.testing: Local Kafka broker up and running on 127.0.0.1:9789\n",
      "[INFO] fastkafka.helpers: create_missing_topics(['preprocessed_signals', 'predictions']): new_topics = [NewTopic(topic=preprocessed_signals,num_partitions=1), NewTopic(topic=predictions,num_partitions=1)]\n",
      "[INFO] fastkafka.application: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:9789'}'\n",
      "[INFO] fastkafka.application: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:9789'}'\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:9789', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'preprocessed_signals'})\n",
      "[INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'preprocessed_signals'}\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Terminating the process 32620...\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:9789', 'auto_offset_reset': 'latest', 'max_poll_records': 100}\n",
      "[INFO] aiokafka.consumer.group_coordinator: Metadata for topic has changed from {} to {'preprocessed_signals': 1}. \n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'predictions'})\n",
      "[INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'predictions'}\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[INFO] aiokafka.consumer.group_coordinator: Metadata for topic has changed from {} to {'predictions': 1}. \n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: KafkaConnectionError: Connection at tvrtko-fastkafka-devel:9789 closed\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: KafkaConnectionError: Connection at tvrtko-fastkafka-devel:9789 closed\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Process 32620 terminated.\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Terminating the process 32254...\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Process 32254 terminated.\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'asyncio' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[9], line 8\u001b[0m\n\u001b[1;32m      2\u001b[0m create_missing_topics(\n\u001b[1;32m      3\u001b[0m     [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpreprocessed_signals\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpredictions\u001b[39m\u001b[38;5;124m\"\u001b[39m],\n\u001b[1;32m      4\u001b[0m     bootstrap_servers\u001b[38;5;241m=\u001b[39mbootstrap_server,\n\u001b[1;32m      5\u001b[0m     num_partitions\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m1\u001b[39m,\n\u001b[1;32m      6\u001b[0m )\n\u001b[1;32m      7\u001b[0m tester \u001b[38;5;241m=\u001b[39m Tester([create_service(bootstrap_servers\u001b[38;5;241m=\u001b[39mbootstrap_server)])\n\u001b[0;32m----> 8\u001b[0m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mwith\u001b[39;00m tester:\n\u001b[1;32m      9\u001b[0m     \u001b[38;5;28;01mawait\u001b[39;00m tester\u001b[38;5;241m.\u001b[39mto_preprocessed_signals(TestMsg(msg\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msignal\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[1;32m     10\u001b[0m     \u001b[38;5;28;01mawait\u001b[39;00m asyncio\u001b[38;5;241m.\u001b[39msleep(\u001b[38;5;241m5\u001b[39m)\n",
      "File \u001b[0;32m/work/fastkafka/fastkafka/application.py:721\u001b[0m, in \u001b[0;36mFastKafka.__aenter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    720\u001b[0m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__aenter__\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[0;32m--> 721\u001b[0m     \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstartup()\n",
      "Cell \u001b[0;32mIn[7], line 26\u001b[0m, in \u001b[0;36mTester.startup\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     24\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mcreate_mocks()\n\u001b[1;32m     25\u001b[0m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28msuper\u001b[39m()\u001b[38;5;241m.\u001b[39mstartup()\n\u001b[0;32m---> 26\u001b[0m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[43masyncio\u001b[49m\u001b[38;5;241m.\u001b[39msleep(\u001b[38;5;241m3\u001b[39m)\n",
      "\u001b[0;31mNameError\u001b[0m: name 'asyncio' is not defined"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka.consumer.fetcher: Failed fetch messages from 0: NodeNotReadyError: Attempt to send a request to node which is not ready (node id 0).\n",
      "[ERROR] aiokafka: Unable connect to node with id 0: [Errno 111] Connect call failed ('172.22.0.6', 9789)\n",
      "[ERROR] aiokafka: Unable to update metadata from [0]\n"
     ]
    }
   ],
   "source": [
    "async with LocalKafkaBroker(zookeeper_port=9998, listener_port=9789) as bootstrap_server:\n",
    "    create_missing_topics(\n",
    "        [\"preprocessed_signals\", \"predictions\"],\n",
    "        bootstrap_servers=bootstrap_server,\n",
    "        num_partitions=1,\n",
    "    )\n",
    "    tester = Tester([create_service(bootstrap_servers=bootstrap_server)])\n",
    "    async with tester:\n",
    "        await tester.to_preprocessed_signals(TestMsg(msg=\"signal\"))\n",
    "        await asyncio.sleep(5)\n",
    "        tester.mocks.on_predictions.assert_called()\n",
    "\n",
    "print(\"ok\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9805156",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
